service: backend
frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/Polls"

functions:
  create:
    handler: api/create.create
    events:
      - http:
          path: create
          method: post
          cors: true
  getAll:
    handler: api/get_all.getAll
    events:
      - http:
          path: all
          method: get
          cors: true

resources:
  Resources:
    PollsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TableName: "Polls"